### ISSUE TITLE
Navigation bar background color

### ISSUE THREAD

**Issue by xmha97** [CliffracerMerchant/SoundAura#25] opened 2022-11-16 11:37 UTC
Hi, on dark theme the background of navigation bar is white (light)
Please fix this issue.
Thanks.

![Screenshot_2022-11-16-15-04-49-513_com.cliffracertech.soundaura.jpg](https://user-images.githubusercontent.com/23485114/202170793-c5367bb3-0375-4b9e-b24c-3642ca435901.jpg)

**Comment by CliffracerMerchant** [comment] 2022-11-16 20:08
On [line 174 from MainActivity.kt](https://github.com/CliffracerMerchant/SoundAura/blob/master/app/src/main/java/com/cliffracertech/soundaura/MainActivity.kt#L174) I set the navigation bar color to transparent so that the background color underneath it shows through. This seems to work fine on my phone and on all of the emulated devices I've tested it on. Do you mind if I ask what device you're having this issue on?

**Comment by xmha97** [comment] 2022-11-17 20:53
My phone is: Xiaomi 11T
https://www.gsmarena.com/xiaomi_11t-11099.php

**Comment by CliffracerMerchant** [comment] 2022-11-17 21:33
Like I said previously I can't reproduce this on my end, so I think this is a manufacturer specific issue. I googled transparent navigation bar MIUI and found [this post](https://forum.xda-developers.com/t/transparent-navbar-nova-miui.3650751/#post-73285562). Do you have this setting on your phone, and does it allow the navigation bar to be transparent if you enable it?

**Comment by xmha97** [comment] 2022-11-18 00:37
> Do you have this setting on your phone?

No

Please look at this app.
https://github.com/mueller-ma/Coffee
It working fine.

![Screenshot_2022-11-18-04-06-20-415_com.github.muellerma.coffee.jpg](https://user-images.githubusercontent.com/23485114/202589729-65ef6a61-a002-4983-ad45-a83a0d21e4b0.jpg)

![Screenshot_2022-11-18-04-06-29-205_com.github.muellerma.coffee.jpg](https://user-images.githubusercontent.com/23485114/202589756-1f53c192-00b7-4922-9676-210c0dcaab4f.jpg)

**Comment by CliffracerMerchant** [comment] 2022-11-18 15:16
I think that app is setting the nav bar color to be a solid color that matches the background. SoundAura is setting the navigation bar to be transparent so that the background underneath shows through. From what I can tell MIUI devices prevent apps from making the nav bar transparent to ensure that it is always visible, and that is causing it to be white on your device.

Obviously I don't want to ruin the transparent nav bar effect on non-MIUI devices by changing it to always be a solid color. I could add an option to use a solid nav bar color instead of making it transparent, but I would rather avoid that too if possible to prevent the settings screen from getting too complicated.

Do you have [this option](https://www.youtube.com/shorts/BTdN6LsAvIM) in your settings screen, and does enabling that prevent the white nav bar color in dark mode? If that doesn't work for you I guess I can add an option to use solid instead of transparent nav bar colors.

**Comment by xmha97** [comment] 2022-11-19 13:01
I don't have this option, but I suggest you don't clutter the settings of this app and ignore this issue.

**Comment by CliffracerMerchant** [comment] 2022-11-19 16:43
Are you sure? I really don't mind adding it if you can't fix it on your end, I was just making sure there was no other option first. Also adding one more setting to the settings screen wouldn't matter that much at this point, and if it ever got to the point where the setting screen was too cluttered I could always add a 'additional settings' screen with less common options.

**Comment by CliffracerMerchant** [comment] 2023-01-23 14:12
When I created a new emulated device, this issue ended up appearing on it. Between that and the fact that Xiaomi devices are not uncommon, I'm going to reopen this and add an option for it in the settings.

**Comment by CliffracerMerchant** [comment] 2023-01-23 18:37
So it turns out that this was my fault after all >_>. This problem is fixed on the one emulated device I encountered it on, and hopefully on yours. If you still have this problem on v1.5.0, feel free to reopen.

**Closed by CliffracerMerchant** 2023-01-23 18:37 UTC
